services:

  brandenburg_db:
    image: postgis/postgis
    container_name: brandenburg_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    volumes:
      - ./data:/work
      - brandenburg_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./services/backend
    container_name: backend
    networks: 
      default:
        aliases:
          - backend
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=brandenburg_db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./services/backend:/app
      - forest_fire_data:/app/data/forest_fire_predictor
      - demographic_data:/app/data/demographic_data
    command: >
      /bin/sh -c "
      uvicorn src.main:app --reload --host 0.0.0.0 --port 5000"
    depends_on:
      - brandenburg_db

  app:
    build: 
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: app
    networks: 
      default:
        aliases:
          - app
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    restart: unless-stopped
  
  tileserv:
    container_name: tileserv
    image: pramsey/pg_tileserv:20231005
    #image: pramsey/pg_tileserv:latest
    env_file:
      - pg_tileserv.env
    volumes:
      - ./services/tileserv/pg_tileserv.toml:/config/pg_tileserv.toml:ro
    depends_on:
      - brandenburg_db
    restart: unless-stopped
    networks:
      default:
        aliases:
          - tileserv

  geoserver:
    image: kartoza/geoserver:latest
    networks: 
      default:
        aliases:
          - geoserver
    container_name: geoserver
    restart: unless-stopped
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_PASSWORD}
    env_file:
      - .env
    depends_on:
      - brandenburg_db
    
  masterportal:
    image: nginx
    container_name: masterportal
    volumes:
      - ./services/masterportal:/usr/share/nginx/html/masterportal
    networks: 
      default:
        aliases:
          - masterportal
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - backend
      - masterportal
      - tileserv
      - geoserver
    restart: unless-stopped

volumes:
  brandenburg_db:
  geoserver_data:
  forest_fire_data:
  demographic_data: